# Generated by Django 5.0 on 2023-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='День')),
                ('predmet', models.CharField(max_length=25, verbose_name='Предмет')),
                ('start', models.TimeField(verbose_name='Начало занятия')),
                ('end', models.TimeField(verbose_name='Конец занятия')),
            ],
        ),
    ]
